<?php

    $etablissements= array (
        "01 - Annecy",
        "02 - Auxerre",
        "03 - Bethune",
        "04 - Beziers",
        "05 - Blagnac",
        "06 - Blois",
        "07 - Caen-Ifs",
        "08 - Chalons-en-Champagne",
        "09 - Clermont-Ferrand",
        "10 - Colmar",
        "11 - Grenoble",
        "12 - Kourou",
        "13 - La Reunion",
        "14 - La Roche sur Yon",
        "15 - La Rochelle",
        "16 - Lannion",
        "17 - Luminy",
        "18 - Mont de Marsan",
        "19 - Montbeliard",
        "20 - Nancy",
        "21 - Poitiers",
        "22 - Roanne",
        "23 - Rouen-Elbeuf",
        "24 - Saint-Malo",
        "25 - Sophia",
        "26 - Valence",
        "27 - Velizy",
        "28 - Villetaneuse",
        "29 - Vitry",
    );
?>